# Generated by Django 5.1.1 on 2024-10-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(choices=[('1 ton truck', '1 ton truck'), ('3 ton truck', '3 ton truck'), ('4.2 ton truck', '4.2 ton truck'), ('7 ton truck', '7 ton truck'), ('12 M truck', '12 M truck'), ('10 ton truck', '10 ton truck'), ('Trailer truck', 'Trailer truck'), ('13.6 M truck', '13.6 M truck'), ('Tipper truck', 'Tipper truck'), ('15 M truck', '15 M truck')], max_length=50)),
                ('packing_type', models.CharField(choices=[('Loose', 'Loose'), ('Box', 'Box'), ('Pallet', 'Pallet'), ('Sacks', 'Sacks'), ('Drums', 'Drums'), ('Others', 'Others')], max_length=50)),
                ('lifters_required', models.BooleanField()),
                ('item_description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrossBorderFreightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('Box', 'Box'), ('Fragile', 'Fragile'), ('Hazardous', 'Hazardous'), ('Loose', 'Loose'), ('Others', 'Others')], max_length=50)),
                ('length', models.FloatField(help_text='Length in meters')),
                ('width', models.FloatField(help_text='Width in meters')),
                ('height', models.FloatField(help_text='Height in meters')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('lifters_required', models.BooleanField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureMovingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('move_home', models.BooleanField()),
                ('home_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Townhouse', 'Townhouse'), ('Penthouse', 'Penthouse'), ('Compound', 'Compound'), ('Whole Building', 'Whole Building'), ('Duplex', 'Duplex'), ('Bulk Units', 'Bulk Units'), ('Hotel Apartment', 'Hotel Apartment'), ('Staff Accommodation', 'Staff Accommodation')], max_length=50, null=True)),
                ('request_visit', models.BooleanField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_from', models.CharField(max_length=100)),
                ('shipping_to', models.CharField(max_length=100)),
                ('furniture_types', models.CharField(blank=True, choices=[('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Balcony', 'Balcony'), ('Dining Room', 'Dining Room'), ('Hallway', 'Hallway'), ('Home Office', 'Home Office'), ('Kitchen', 'Kitchen'), ('Living Room', 'Living Room'), ('Garden', 'Garden'), ('Gaming Room', 'Gaming Room')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalShipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Motorbike', 'Motorbike'), ('Pickup 2 Tons', 'Pickup 2 Tons'), ('Pickup 4 Tons', 'Pickup 4 Tons'), ('Van', 'Van')], max_length=50)),
                ('material_type', models.CharField(choices=[('Box', 'Box'), ('Fragile', 'Fragile'), ('Hazardous', 'Hazardous'), ('Loose', 'Loose'), ('Others', 'Others')], max_length=50)),
                ('item_description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('commercial_retail', models.CharField(choices=[('Commercial', 'Commercial'), ('Retail', 'Retail')], max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('Car', 'Car'), ('Motorbike', 'Motorbike'), ('Pickup 2 Tons', 'Pickup 2 Tons'), ('Pickup 4 Tons', 'Pickup 4 Tons'), ('Van', 'Van')], max_length=50, null=True)),
                ('material_type', models.CharField(choices=[('Box', 'Box'), ('Fragile', 'Fragile'), ('Hazardous', 'Hazardous'), ('Loose', 'Loose'), ('Others', 'Others')], max_length=50)),
                ('brief_description', models.CharField(max_length=255)),
                ('pick_up_time', models.TimeField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('lifters_required', models.BooleanField()),
                ('shipping_from', models.CharField(max_length=100)),
                ('shipping_to', models.CharField(max_length=100)),
            ],
        ),
    ]
