# Generated by Django 5.1.1 on 2024-10-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='constructionrequest',
            name='truck_type',
        ),
        migrations.RemoveField(
            model_name='shippingrequest',
            name='commercial_retail',
        ),
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='shippingrequest',
            name='is_commercial',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furnituremoving',
            name='furniture_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.furnituretype'),
        ),
        migrations.AlterField(
            model_name='furnituremoving',
            name='home_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.hometype'),
        ),
        migrations.AlterField(
            model_name='constructionrequest',
            name='packing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.materialtype'),
        ),
        migrations.AlterField(
            model_name='crossborderfreight',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.materialtype'),
        ),
        migrations.AlterField(
            model_name='personalshipment',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.materialtype'),
        ),
        migrations.AlterField(
            model_name='shippingrequest',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.materialtype'),
        ),
        migrations.AddField(
            model_name='constructionrequest',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.vehicletype'),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.vehicletype'),
        ),
        migrations.AlterField(
            model_name='personalshipment',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.vehicletype'),
        ),
        migrations.AlterField(
            model_name='shippingrequest',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.vehicletype'),
        ),
    ]
