# Generated by Django 5.1.1 on 2024-10-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('MotorCycle', 'MotorCycle'), ('Motorcycle', 'Motorcycle'), ('Sedan Car', 'Sedan Car'), ('Pickup Truck', 'Pickup Truck'), ('Low Bed Trailer', 'Low Bed Trailer'), ('Flat Bed Trailer', 'Flat Bed Trailer'), ('Chiller Truck', 'Chiller Truck'), ('Garbage Removal Truck', 'Garbage Removal Truck'), ('Canter Truck', 'Canter Truck')], max_length=50)),
                ('number_of_vehicle', models.PositiveIntegerField()),
                ('driver_required', models.BooleanField()),
                ('lifters_required', models.BooleanField()),
                ('item_description', models.TextField()),
                ('shipping_from', models.CharField(max_length=100)),
                ('shipping_to', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
